name: Lint and test code
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  e2e-test:
    name: E2E test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [ "v1.15.12", "v1.16.15", "v1.17.17", "v1.18.16", "v1.19.8", "v1.20.4" ]
    env:
      DOCKER_BUILDKIT: '1' # Setting DOCKER_BUILDKIT=1 ensures TARGETOS and TARGETARCH are populated
    steps:
      - uses: actions/checkout@v2
      - uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: v1.17.1
          kubernetes version: ${{ matrix.k8s-version }}
          driver: docker
      - name: Run e2e test
        continue-on-error: ${{ contains(matrix.k8s-version, '1.20') }} # experimental support for 1.20.x
        run: |
          # make minikube use local docker registry
          eval $(minikube -p minikube docker-env)

          # createa docker image and use it in minikube
          DOCKER_IMAGE_TAG=e2e-test make e2e-test
