name: Lint and test code
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  e2e-test:
    name: E2E test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s_version: ["v1.15.12", "v1.16.15", "v1.17.14", "v1.18.12", "v1.19.4"]
    steps:
      - uses: actions/checkout@v2
      - uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: v1.17.1
          kubernetes version: ${{ matrix.k8s_version }}
          driver: docker
      - name: Run e2e test
        run: |
          # make minikube use local docker registry
          eval $(minikube -p minikube docker-env)

          # createa docker image and use it in minikube
          make DOCKER_IMAGE_TAG=e2e-test e2e-test
