name: Release
on:
  release:
    types:
      - prereleased
      - released

env: 
 
  DOCKER_IMAGE_NAME: newrelic/k8s-webhook-cert-manager
  DOCKER_IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from release tag
        run: |
          echo "DOCKER_IMAGE_TAG=$(echo $DOCKER_IMAGE_TAG | grep -oE '([0-9.]*[0-9])$')" >> $GITHUB_ENV

      - name: Test for prerelase
        if: ${{ github.event.release.prerelease }}
        run: |
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG-pre" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.FSI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FSI_DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          make build-container
          docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - name: Tag and push latest
        if: ${{ ! github.event.release.prerelease }}
        run: |
          docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:latest
          docker push $DOCKER_IMAGE_NAME:latest
          