name: Release
on:
  release:
    types:
      - prereleased
      - released

env: 
 
  DOCKER_IMAGE: newrelic/k8s-webhook-cert-manager
  RELEASE_VERSION: ${{ github.event.release.tag_name }}
  S3_PATH: s3://nr-downloads-main/infrastructure_agent
  PRERELEASE: ${{ github.event.release.prerelease }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from release tag
        run: |
          echo "RELEASE_VERSION=$(echo $RELEASE_VERSION | grep -oE '([0-9.]*[0-9])$')" >> $GITHUB_ENV

      - name: Test for prerelase
        if: ${{ github.event.release.prerelease }}
        run: |
          echo "RELEASE_VERSION=$RELEASE_VERSION-pre" >> $GITHUB_ENV
          echo "S3_PATH=$S3_PATH/test" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.FSI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FSI_DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE }}
          DOCKER_IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          make build-container
          docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

          # push 'latest' if NOT pre-release
          if [[ -z "$PRERELEASE" || "false" == "$PRERELEASE" ]]; then
            docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:latest
            docker push $DOCKER_IMAGE_NAME:latest
          fi
